### ISSUE TITLE
kubectl-kubesec uri update

### ISSUE THREAD

**Issue by denhamparry** [kubernetes-sigs/krew-index#1165]
When installing kubectl-kubesec, the homepage directs towards the repo https://github.com/stefanprodan/kubectl-kubesec and then get forwarded to https://github.com/controlplaneio/kubectl-kubesec.

To avoid confusion, recommend changing the homepage/uri to https://github.com/controlplaneio/kubectl-kubesec for kubectl-kubesec.

**Comment by ahmetb** [comment]
opening #1166 is sufficient.
/close
