### ISSUE TITLE
Can't install kconfig from krew

### ISSUE THREAD

**Issue by khaledE** [kubernetes-sigs/krew-index#1241]
Hello,

I'm trying to install kconfig via krew but I keep getting the following :

```
Updated the local copy of plugin index.
F0428 08:37:06.148384   98646 root.go:79] plugin "kconfig" does not exist in the plugin index
```

for reference I get this when I run krew version 

```
GitTag            v0.4.1
GitCommit         ffa2933
IndexURI          https://github.com/kubernetes-sigs/krew-index.git
DetectedPlatform  darwin/amd64
```

Any ideas ?

Thanks
K

**Comment by ahmetb** [comment]
I don't think we have a plugin named as that. https://krew.sigs.k8s.io/plugins
/close

**Comment by khaledE** [comment]
ahhh it's konfig ... sorry my bad!
