### ISSUE TITLE
keep ingress-nginx updated

### ISSUE THREAD

**Issue by terryzwt** [kubernetes-sigs/krew-index#1495]
https://github.com/kubernetes/ingress-nginx/releases

**Comment by ahmetb** [comment]
This is something the maintainers of that repo need to do. So closing the issue here.  

You can tell the developers this message:

> Please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

/close
