### ISSUE TITLE
failed to download and verify file

### ISSUE THREAD

**Issue by redno2** [kubernetes-sigs/krew-index#159]
The checksum does't work, the verify failed

./kubectl krew install oidc-login
Updated the local copy of plugin index.
Installing plugin: oidc-login
W0607 15:43:06.730882   31022 install.go:132] failed to install plugin "oidc-login": failed to dowload and move during installation: failed to download and verify file: checksum does not match, want: 5a4c02dc2527f20ba55f7a0751628d009d5e9a3a5e0efd1d01096ec32869b493, got 64cc80a1cec5a7688ad5632a647640d5d4da8d9bac478f79a289cb5d1620dd93
F0607 15:43:06.731073   31022 root.go:52] failed to install some plugins: [oidc-login]

## Verbose
./kubectl krew install -v 9 oidc-login
I0607 16:10:10.160189    7814 update.go:47] Updating the local copy of plugin index (/home/user/.krew/index)
I0607 16:10:10.160265    7814 git.go:62] Going to run git pull --ff-only -v
Depuis https://github.com/GoogleContainerTools/krew-index
 = [à jour]          master         -> origin/master
 = [à jour]          ahmetb-patch-1 -> origin/ahmetb-patch-1
Déjà à jour.
Updated the local copy of plugin index.
I0607 16:10:10.767747    7814 scanner.go:74] Reading plugin "oidc-login"
I0607 16:10:10.768349    7814 install.go:119] Will install plugin: oidc-login
Installing plugin: oidc-login
I0607 16:10:10.768366    7814 install.go:74] Looking for installed versions
I0607 16:10:10.768376    7814 util.go:79] Searching for installed versions of oidc-login in "/home/user/.krew/bin"
I0607 16:10:10.768397    7814 install.go:83] Finding download target for plugin oidc-login
I0607 16:10:10.768404    7814 util.go:38] Using os=linux arch=amd64
I0607 16:10:10.768409    7814 util.go:61] Matching platform for labels(arch=amd64,os=linux)
I0607 16:10:10.768450    7814 util.go:68] Found matching platform with index (0)
I0607 16:10:10.768457    7814 util.go:131] Matching plugin version is 5a4c02dc2527f20ba55f7a0751628d009d5e9a3a5e0efd1d01096ec32869b493
I0607 16:10:10.768464    7814 install.go:46] Creating download dir "/tmp/krew-downloads/oidc-login"
I0607 16:10:10.768528    7814 install.go:61] Getting sha256 (5a4c02dc2527f20ba55f7a0751628d009d5e9a3a5e0efd1d01096ec32869b493) signed version
I0607 16:10:10.768539    7814 downloader.go:36] Fetching "https://github.com/int128/kubelogin/releases/download/v1.12.0/kubelogin_linux_amd64.zip"
I0607 16:11:11.748254    7814 downloader.go:43] Reading download data into memory
I0607 16:11:11.749183    7814 downloader.go:48] Read 3635 bytes of download data into memory
W0607 16:11:11.749534    7814 install.go:132] failed to install plugin "oidc-login": failed to dowload and move during installation: failed to download and verify file: checksum does not match, want: 5a4c02dc2527f20ba55f7a0751628d009d5e9a3a5e0efd1d01096ec32869b493, got 4be19bfbdcea1b9594b436abc5ec59f7e68168e3c7189a3edaed977499aa5619
F0607 16:11:11.749611    7814 root.go:50] failed to install some plugins: [oidc-login]
github.com/GoogleContainerTools/krew/cmd/krew/cmd.init.1.func1
        /go/src/github.com/GoogleContainerTools/krew/cmd/krew/cmd/install.go:142
github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra.(*Command).execute
        /go/src/github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra/command.go:762
github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /go/src/github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra/command.go:852
github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra.(*Command).Execute
        /go/src/github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra/command.go:800
github.com/GoogleContainerTools/krew/cmd/krew/cmd.Execute
        /go/src/github.com/GoogleContainerTools/krew/cmd/krew/cmd/root.go:48
main.main
        /go/src/github.com/GoogleContainerTools/krew/cmd/krew/main.go:23
runtime.main
        /usr/local/go/src/runtime/proc.go:201
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1333

**Comment by ahmetb** [comment]
I am not able to repro this on my macOS:

   KREW_OS=linux KREW_ARCH=amd64 kubectl krew install oidc-login -v=0

```
I0607 10:44:52.307767   14217 install.go:61] Getting sha256 (5a4c02dc2527f20ba55f7a0751628d009d5e9a3a5e0efd1d01096ec32869b493) signed version
I0607 10:44:52.307783   14217 downloader.go:36] Fetching "https://github.com/int128/kubelogin/releases/download/v1.12.0/kubelogin_linux_amd64.zip"
I0607 10:44:53.158447   14217 downloader.go:43] Reading download data into memory
I0607 10:44:54.672119   14217 downloader.go:48] Read 8761242 bytes of download data into memory
```

In your case it says `Read 3635 bytes of download data into memory`.

Looks like you're served a different page on the URL (somehow)? Is this reproducible? Can you go to `https://github.com/int128/kubelogin/releases/download/v1.12.0/kubelogin_linux_amd64.zip` and see what it is?

**Comment by redno2** [comment]
I'm on ubuntu.

Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic

If I download via curl the hash is matching:
$curl -OL https://github.com/int128/kubelogin/releases/download/v1.12.0/kubelogin_linux_amd64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   616    0   616    0     0   1720      0 --:--:-- --:--:-- --:--:--  1720
100 8555k  100 8555k    0     0   540k      0  0:00:15  0:00:15 --:--:--  885k
$sha256sum kubelogin_linux_amd64.zip 
5a4c02dc2527f20ba55f7a0751628d009d5e9a3a5e0efd1d01096ec32869b493  kubelogin_linux_amd64.zip


thanks

**Comment by ahmetb** [comment]
Is this reproducibly failing? How many bytes downloaded does the logs say?

**Comment by redno2** [comment]
Mhh super weird, usually is failing to install but sometime it's worked..
I tried it inside a lxc with a fresh config, I'm behind a corporate proxy.
Tried 3 time and the 4th it worked, and at each time the hash is different.. I suspect the redirect url is pointing to an old version of the release !?


root@kubectl:/tmp# kubectl krew install rbac-lookup
Updated the local copy of plugin index.
Installing plugin: rbac-lookup


W0613 14:17:24.466722    2009 install.go:132] failed to install plugin "rbac-lookup": failed to dowload and move during installation: failed to download and verify file: checksum does not match, want: a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141, got e08cb4433d81c9c781e7c2b2b46ea9397c1bf3f57360efe2c7d16a8304a4793a
F0613 14:17:24.466800    2009 root.go:52] failed to install some plugins: [rbac-lookup]
root@kubectl:/tmp# 
root@kubectl:/tmp# 
root@kubectl:/tmp# 
root@kubectl:/tmp# kubectl krew install rbac-lookup
Updated the local copy of plugin index.
Installing plugin: rbac-lookup






W0613 14:18:30.469261    2067 install.go:132] failed to install plugin "rbac-lookup": failed to dowload and move during installation: failed to download and verify file: checksum does not match, want: a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141, got 8bbd3d10ff1715f349ae731c6d6ea84880586559a199b13d810fe583999b917e
F0613 14:18:30.469345    2067 root.go:52] failed to install some plugins: [rbac-lookup]
root@kubectl:/tmp# 
root@kubectl:/tmp# 
root@kubectl:/tmp# 
root@kubectl:/tmp# 
root@kubectl:/tmp# 
root@kubectl:/tmp# 
root@kubectl:/tmp# kubectl krew install rbac-lookup
Updated the local copy of plugin index.
Installing plugin: rbac-lookup

W0613 14:22:15.468121    2122 install.go:132] failed to install plugin "rbac-lookup": failed to dowload and move during installation: failed to download and verify file: checksum does not match, want: a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141, got 30dadbd98b8d96aad8c5552638aead62221fa7d17963a58274d43e8c5df7f7bf
F0613 14:22:15.468218    2122 root.go:52] failed to install some plugins: [rbac-lookup]
root@kubectl:/tmp# 
root@kubectl:/tmp# kubectl krew install rbac-lookup -v 9
I0613 14:22:30.043765    2179 update.go:47] Updating the local copy of plugin index (/root/.krew/index)
I0613 14:22:30.043962    2179 git.go:62] Going to run git pull --ff-only -v
From https://github.com/GoogleContainerTools/krew-index
 = [up to date]      master         -> origin/master
 = [up to date]      ahmetb-patch-1 -> origin/ahmetb-patch-1
Already up to date.
Updated the local copy of plugin index.
I0613 14:22:30.661772    2179 scanner.go:74] Reading plugin "rbac-lookup"
I0613 14:22:30.662497    2179 install.go:119] Will install plugin: rbac-lookup
Installing plugin: rbac-lookup
I0613 14:22:30.662518    2179 install.go:74] Looking for installed versions
I0613 14:22:30.662676    2179 util.go:79] Searching for installed versions of rbac-lookup in "/root/.krew/bin"
I0613 14:22:30.662702    2179 install.go:83] Finding download target for plugin rbac-lookup
I0613 14:22:30.662714    2179 util.go:38] Using os=linux arch=amd64
I0613 14:22:30.662723    2179 util.go:61] Matching platform for labels(arch=amd64,os=linux)
I0613 14:22:30.662795    2179 util.go:68] Found matching platform with index (1)
I0613 14:22:30.662805    2179 util.go:131] Matching plugin version is a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141
I0613 14:22:30.662814    2179 install.go:46] Creating download dir "/tmp/krew-downloads/rbac-lookup"
I0613 14:22:30.662942    2179 install.go:61] Getting sha256 (a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141) signed version
I0613 14:22:30.662956    2179 downloader.go:36] Fetching "https://github.com/reactiveops/rbac-lookup/releases/download/v0.3.0/rbac-lookup_0.3.0_Linux_x86_64.tar.gz"





I0613 14:23:32.468062    2179 downloader.go:43] Reading download data into memory
I0613 14:23:32.468757    2179 downloader.go:48] Read 3659 bytes of download data into memory
W0613 14:23:32.468985    2179 install.go:132] failed to install plugin "rbac-lookup": failed to dowload and move during installation: failed to download and verify file: checksum does not match, want: a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141, got c939366538e813c6839f48bc9f217aa1c1df2b39e2555354e40dab9169bbab28
F0613 14:23:32.469021    2179 root.go:50] failed to install some plugins: [rbac-lookup]
github.com/GoogleContainerTools/krew/cmd/krew/cmd.init.1.func1
        /go/src/github.com/GoogleContainerTools/krew/cmd/krew/cmd/install.go:142
github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra.(*Command).execute
        /go/src/github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra/command.go:762
github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /go/src/github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra/command.go:852
github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra.(*Command).Execute
        /go/src/github.com/GoogleContainerTools/krew/vendor/github.com/spf13/cobra/command.go:800
github.com/GoogleContainerTools/krew/cmd/krew/cmd.Execute
        /go/src/github.com/GoogleContainerTools/krew/cmd/krew/cmd/root.go:48
main.main
        /go/src/github.com/GoogleContainerTools/krew/cmd/krew/main.go:23
runtime.main
        /usr/local/go/src/runtime/proc.go:201
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1333
root@kubectl:/tmp# 
root@kubectl:/tmp# 
root@kubectl:/tmp# 
root@kubectl:/tmp# 
root@kubectl:/tmp# 
root@kubectl:/tmp# locate downloader.go
root@kubectl:/tmp# updatedb
root@kubectl:/tmp# locate downloader.go
root@kubectl:/tmp# kubectl krew install rbac-lookup -v 9
I0613 14:25:01.333190    2238 update.go:47] Updating the local copy of plugin index (/root/.krew/index)
I0613 14:25:01.333256    2238 git.go:62] Going to run git pull --ff-only -v
From https://github.com/GoogleContainerTools/krew-index
 = [up to date]      master         -> origin/master
 = [up to date]      ahmetb-patch-1 -> origin/ahmetb-patch-1
Already up to date.
Updated the local copy of plugin index.
I0613 14:25:02.443065    2238 scanner.go:74] Reading plugin "rbac-lookup"
I0613 14:25:02.443509    2238 install.go:119] Will install plugin: rbac-lookup
Installing plugin: rbac-lookup
I0613 14:25:02.443524    2238 install.go:74] Looking for installed versions
I0613 14:25:02.443535    2238 util.go:79] Searching for installed versions of rbac-lookup in "/root/.krew/bin"
I0613 14:25:02.443549    2238 install.go:83] Finding download target for plugin rbac-lookup
I0613 14:25:02.443556    2238 util.go:38] Using os=linux arch=amd64
I0613 14:25:02.443563    2238 util.go:61] Matching platform for labels(arch=amd64,os=linux)
I0613 14:25:02.443624    2238 util.go:68] Found matching platform with index (1)
I0613 14:25:02.443632    2238 util.go:131] Matching plugin version is a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141
I0613 14:25:02.443638    2238 install.go:46] Creating download dir "/tmp/krew-downloads/rbac-lookup"
I0613 14:25:02.443745    2238 install.go:61] Getting sha256 (a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141) signed version
I0613 14:25:02.443757    2238 downloader.go:36] Fetching "https://github.com/reactiveops/rbac-lookup/releases/download/v0.3.0/rbac-lookup_0.3.0_Linux_x86_64.tar.gz"
^C
root@kubectl:/tmp# ls -al /tmp/krew-downloads/rbac-lookup
total 1
drwxr-xr-x 2 root root 2 Jun 13 14:25 .
drwxr-xr-x 3 root root 3 Jun 13 14:25 ..
root@kubectl:/tmp# kubectl krew install rbac-lookup -v 9 
I0613 14:25:19.471388    2293 update.go:47] Updating the local copy of plugin index (/root/.krew/index)
I0613 14:25:19.471447    2293 git.go:62] Going to run git pull --ff-only -v
From https://github.com/GoogleContainerTools/krew-index
 = [up to date]      master         -> origin/master
 = [up to date]      ahmetb-patch-1 -> origin/ahmetb-patch-1
Already up to date.
Updated the local copy of plugin index.
I0613 14:25:20.076371    2293 scanner.go:74] Reading plugin "rbac-lookup"
I0613 14:25:20.076921    2293 install.go:119] Will install plugin: rbac-lookup
Installing plugin: rbac-lookup
I0613 14:25:20.076936    2293 install.go:74] Looking for installed versions
I0613 14:25:20.076956    2293 util.go:79] Searching for installed versions of rbac-lookup in "/root/.krew/bin"
I0613 14:25:20.076981    2293 install.go:83] Finding download target for plugin rbac-lookup
I0613 14:25:20.076993    2293 util.go:38] Using os=linux arch=amd64
I0613 14:25:20.077005    2293 util.go:61] Matching platform for labels(arch=amd64,os=linux)
I0613 14:25:20.077074    2293 util.go:68] Found matching platform with index (1)
I0613 14:25:20.077082    2293 util.go:131] Matching plugin version is a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141
I0613 14:25:20.077092    2293 install.go:46] Creating download dir "/tmp/krew-downloads/rbac-lookup"
I0613 14:25:20.077114    2293 install.go:61] Getting sha256 (a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141) signed version
I0613 14:25:20.077128    2293 downloader.go:36] Fetching "https://github.com/reactiveops/rbac-lookup/releases/download/v0.3.0/rbac-lookup_0.3.0_Linux_x86_64.tar.gz"
I0613 14:25:24.197053    2293 downloader.go:43] Reading download data into memory
I0613 14:25:38.880914    2293 downloader.go:48] Read 9420289 bytes of download data into memory
I0613 14:25:38.880954    2293 downloader.go:177] detected .tar.gz file
I0613 14:25:38.880963    2293 downloader.go:93] tar: extracting to "/tmp/krew-downloads/rbac-lookup"
I0613 14:25:38.881489    2293 downloader.go:110] tar: processing "LICENSE" (type=48, mode=-rw-r--r--)
I0613 14:25:38.881510    2293 downloader.go:125] tar: ensuring parent dirs exist for regular file, dir=/tmp/krew-downloads/rbac-lookup
I0613 14:25:38.881739    2293 downloader.go:139] tar: processed "LICENSE"
I0613 14:25:38.881766    2293 downloader.go:110] tar: processing "README.md" (type=48, mode=-rw-r--r--)
I0613 14:25:38.881779    2293 downloader.go:125] tar: ensuring parent dirs exist for regular file, dir=/tmp/krew-downloads/rbac-lookup
I0613 14:25:38.881879    2293 downloader.go:139] tar: processed "README.md"
I0613 14:25:38.881897    2293 downloader.go:110] tar: processing "rbac-lookup" (type=48, mode=-rwxr-xr-x)
I0613 14:25:38.881906    2293 downloader.go:125] tar: ensuring parent dirs exist for regular file, dir=/tmp/krew-downloads/rbac-lookup
I0613 14:25:39.158146    2293 downloader.go:139] tar: processed "rbac-lookup"
I0613 14:25:39.158178    2293 downloader.go:141] tar extraction to /tmp/krew-downloads/rbac-lookup complete
I0613 14:25:39.158214    2293 move.go:155] Creating plugin dir "/root/.krew/store/rbac-lookup"
I0613 14:25:39.158488    2293 move.go:161] Creating temp plugin move operations dir "/tmp/krew-temp-move699443671"
I0613 14:25:39.158502    2293 move.go:125] Finding move targets from "/tmp/krew-downloads/rbac-lookup" to "/tmp/krew-temp-move699443671" with file operation=index.FileOperation{From:"*", To:"."}
I0613 14:25:39.158526    2293 move.go:44] Trying to move single file directly from="/tmp/krew-downloads/rbac-lookup" to="/tmp/krew-temp-move699443671" with file operation=index.FileOperation{From:"*", To:"."}
I0613 14:25:39.158551    2293 move.go:52] Wasn't a single file, proceeding with Glob move
I0613 14:25:39.158624    2293 move.go:132] Move file from "/tmp/krew-downloads/rbac-lookup/LICENSE" to "/tmp/krew-temp-move699443671/LICENSE"
I0613 14:25:39.158710    2293 move.go:132] Move file from "/tmp/krew-downloads/rbac-lookup/README.md" to "/tmp/krew-temp-move699443671/README.md"
I0613 14:25:39.158774    2293 move.go:132] Move file from "/tmp/krew-downloads/rbac-lookup/rbac-lookup" to "/tmp/krew-temp-move699443671/rbac-lookup"
I0613 14:25:39.158832    2293 move.go:141] Move operations are complete
I0613 14:25:39.158842    2293 move.go:172] Move directory "/tmp/krew-temp-move699443671" to "/root/.krew/store/rbac-lookup/a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141"
I0613 14:25:39.159054    2293 install.go:159] No file found at "/root/.krew/bin/kubectl-rbac_lookup"
I0613 14:25:39.159070    2293 install.go:146] Creating symlink from "/root/.krew/store/rbac-lookup/a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141/rbac-lookup" to "/root/.krew/bin/kubectl-rbac_lookup"
I0613 14:25:39.159136    2293 install.go:150] Created symlink at "/root/.krew/bin/kubectl-rbac_lookup"
Installed plugin: rbac-lookup

**Comment by redno2** [comment]
I'll doing tests outside our network just to be sure..

**Comment by ahmetb** [comment]
I tried downloading https://github.com/reactiveops/rbac-lookup/releases/download/v0.3.0/rbac-lookup_0.3.0_Linux_x86_64.tar.gz multiple times, and it seems like I get consistent checksum listed in the plugin manifest:

```
$ while :; do curl -sSL https://github.com/reactiveops/rbac-lookup/releases/download/v0.3.0/rbac-lookup_0.3.0_Linux_x86_64.tar.gz | sha256sum; done
a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141  -
a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141  -
a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141  -
a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141  -
a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141  -
a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141  -
a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141  -
a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141  -
a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141  -
a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141  -
a758133ce7c0e056f6cd90dc12b33c0c0f63c8adec37041b25891e54880db141  -
^C
```

I suspect your network proxy does something rather interesting. Since the URL is HTTPS, I am thinking your corp proxy has CA certs installed your machine to intercept your traffic to `https://github.com` and might be modifying it.

**Comment by corneliusweig** [comment]
Hi @redno2, have you had a chance to perform some download tests outside of your corporate firewall?

**Comment by ahmetb** [comment]
/close
due to inactivity.
I suspect it's not a krew issue.

**Comment by redno2** [comment]
> Hi @redno2, have you had a chance to perform some download tests outside of your corporate firewall?

Hi, sorry for the delay. Yes it was a misconfiguration with our internal proxy.
Thank you.
