### ISSUE TITLE
Overview page for plugins

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew-index#179]
Currently, there is no web-compatible way to show a nicely formatted list of plugins in `krew-index`.

@ahmetb Suggested to have a markdown page with a list of plugins to fill that gap. This page has to be generated by a script. At the bare minimum, this `plugins.md` overview should show a table of plugin names + shortDescription. It would be nice to also show additional information, such as github stars via https://shields.io.

See also https://github.com/kubernetes-sigs/krew/issues/192

**Comment by corneliusweig** [comment]
I think that such a script quickly becomes un-maintainable when implemented in shell. Since `krew` is also written in go, I'd suggest to implement the script as a small `go run` script.

**Comment by ahmetb** [comment]
Likely the tool would live in `krew` repo (like `validate-krew-manifest`) so I recommend transferring the issue there.

**Comment by corneliusweig** [comment]
Do you want to keep `krew-index` free of code/logic? Otherwise, I would see the generator more in this repo.

**Comment by ahmetb** [comment]
Yeah, since we ship this repo to every krew user's computer I'd love to keep it minimal.

**Comment by corneliusweig** [comment]
Yeah, right :man_facepalming:
