### ISSUE TITLE
[question] Download metrics for plugins installed using Krew

### ISSUE THREAD

**Issue by OGtrilliams** [kubernetes-sigs/krew-index#2068]
I apologize if this is documented somewhere that I haven't found yet, but is there any way to access download numbers for specific plugins downloaded using `kubectl krew`? I'm specifically looking for download numbers for `preflight` & `support-bundle`. Thanks to anyone who can help!

**Comment by chriskim06** [comment]
hi! we have some statistics [here](https://datastudio.google.com/reporting/f74370a0-adcf-4cec-b7bd-a58c638948f5/page/Ufl7). some detail on those stats are in [the docs](https://krew.sigs.k8s.io/docs/developer-guide/plugin-stats/). hope this helps!

**Comment by ahmetb** [comment]
I noticed the download numbers for these plugins suddenly dropped earlier this year, there's a chance we might be looking at last N tags (or you deleted your old tags or something like that).

/close
/kind support
