### ISSUE TITLE
[Question] Docs say use semver but linter enforces a 'v' to be prefixed. 

### ISSUE THREAD

**Issue by rumstead** [kubernetes-sigs/krew-index#2191]
https://semver.org/#is-v123-a-semantic-version

https://github.com/kubernetes-sigs/krew/blob/eda76d9eb403f290d3f25b7b2930b51f170a1312/internal/installation/semver/version.go#L45

Why is 'v' forced to be present, while stating we should use semver versioning?

**Comment by ahmetb** [comment]
This is a bit of a bike shedding discussion. The ecosystem already broadly adopts the v prefix. We can remove there restriction in the future. I doubt we are tied to it.

**Comment by rumstead** [comment]
I agree. At the minimum, it would be helpful to note in the docs that "v" is required. 

The docs say "# 'version' is a valid semantic version string (see semver.org)" and then semver.org proceeds to say that "v" is not valid semantic versioning. 

https://krew.sigs.k8s.io/docs/developer-guide/plugin-manifest/

**Comment by ahmetb** [comment]
Ack, feel free to send a patch editing the comment on the inline yaml.
/good-first-issue
/kind docs

**Comment by rumstead** [comment]
@ahmetb done

**Comment by rumstead** [comment]
https://github.com/kubernetes-sigs/krew/pull/766
