### ISSUE TITLE
How to install plugin that have 2 words in name to preserve spaces?

### ISSUE THREAD

**Issue by etopeter** [kubernetes-sigs/krew-index#228]
I'm maintaining plugin kubectl-view-utilization. Upon installation it renames binary `kubectl-view-utilization` to `kubectl-view_utilization`. 
By naming convention kubectl recognizes `-` and `_` and allows to use spaces between commands if `-` is used. Why krew is renaming binary and how to change this behavior?

**Comment by corneliusweig** [comment]
This is not possible with krew, see https://github.com/kubernetes-sigs/krew/blob/master/docs/DEVELOPER_GUIDE.md#specifying-plugin-executable.

I think the reason why we want to avoid this is to not interfere with builtin commands. For example, a plugin could be called `kubectl-get-pods`, but it would not be called when running `kubectl get pods` (the builtin command is run instead).

**Comment by ahmetb** [comment]
An executable named kubectl-a-b would mean it’s invocable both as:
- kubectl a b
- kubectl a-b

The underscore leaves no room for ambiguity. And we want plugin name to match the invocation.

**Comment by etopeter** [comment]
Thank you for taking time to explain that. It does make sense. I think aliases are the only option to make long plugin names with hyphens more user friendly.
