### ISSUE TITLE
Auto-accept version bumps for plugins

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew-index#233]
Currently, most PRs in krew-index require no manual review as they just bump the version of a plugin.

We need a bot to look at the PRs, note that only `url`/`sha256`/`version` fields are changed and:
- `spec.version` moved forward
- only version part in the `url` has changed and that's the same as spec.version.

In the long run, we can automatically create a batch PR to bump up the plugin versions by looking at repositories the plugins are coming from and their available releases (once a day or so), but that can come later.

If I can find some free time, I'm planning to:

1. use github webhooks to detect `created` and `synchronized` push events
2. use patch link of the PR to understand the patch.
3. using https://godoc.org/github.com/sourcegraph/go-diff/diff or something simpler, look at the patch, and see if it is exactly doing a trivial version bump.
4. if so, approve by commenting `/lgtm` `/approve` from my account, or we can create a bot account.

The code doesn't have to live in krew, this may live on a personal repo and can be deployed to something like Cloud Run to handle github webhook invocations.

/kind proposal

**Comment by ahmetb** [comment]
Heads-up @corneliusweig I'm enabling auto bump checks on this repo. It might be annoying, in that case ping me and I'll close.

**Comment by ahmetb** [comment]
The source code I used can be found at https://github.com/ahmetb/krew-index-autoapprove .

**Comment by corneliusweig** [comment]
I think the auto-approver has proven it's usefulness and stability quite well.

@ahmetb Are you still planning to use a different Github account for this? Otherwise, I think you can close this.

**Comment by ahmetb** [comment]
Lets keep this open maybe we can add the tool here as a cmd somehow.

**Comment by papuneftali** [comment]
Duplicate of #

**Comment by ahmetb** [comment]
> Duplicate of #

@papuneftali you are warned, again.

**Comment by ahmetb** [comment]
OK it seems like this is working pretty well now.
Time to call it resolved.
/close
/hold cancel
