### ISSUE TITLE
Bring plugins from awesome-kubectl-plugins to krew

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew-index#349]
I just discovered https://github.com/ishantanu/awesome-kubectl-plugins which lists a lot of good kubectl plugins that aren't hosted on Krew.

It would be good if we can open issues there to make the plugins developers out there aware of krew. This is something that we've done in the past and it helps foster the plugin ecosystem. It's a win-win for both plugin devs and krew.

/cc @corneliusweig 
/cc @ferhatelmas

**Comment by corneliusweig** [comment]
I opened issues in all the repos that could make sense to bring in. If I missed anything here, please let me know

- [ ] https://github.com/brosandilabs/kubectl-tmux-logs/issues/4
- [ ] https://github.com/kvaps/kubectl-enter/issues/2
- [ ] https://github.com/auth0/k8s-pixy-auth/issues/22
- [ ] https://github.com/bouk/kubectl-dashboard/issues/1
- [ ] https://github.com/makocchi-git/kubectl-free/issues/4
- [ ] https://github.com/IuryAlves/kubectl-ssh/issues/1
- [ ] https://github.com/esin/kubectlsafe/issues/1
- [ ] https://github.com/karancode/kubepod/issues/1
- [ ] https://github.com/bmuschko/kubectl-swiftnp/issues/2
- [ ] https://github.com/fabiand/kubectl-plugin-pvc/issues/4
- [ ] https://github.com/rafi/kubectl-pass/issues/1
- [ ] https://github.com/cststack/km/issues/1
- [ ] https://github.com/mousavian/kubectl-rotate-pods/issues/2
- [ ] https://github.com/howardjohn/kubectl-resources/issues/24
- [ ] https://github.com/pr8kerl/kubectl-ssm-secret/issues/1
- [ ] https://github.com/makocchi-git/kubectl-dfi/issues/4

**Comment by evalsocket** [comment]
@ahmetb It looks good for beginner.  Would like to work on this. Can this be assigned to me ?

**Comment by ahmetb** [comment]
Don’t work on this Please. This is for plugin authors to bring their own plugins.

**Comment by corneliusweig** [comment]
I don't think there's much more we can do right now. Most of the issues are still open in the plugin repos.
