### ISSUE TITLE
virt.yaml checksum mismatch

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew-index#390]
install failing

> W1217 13:51:22.308846   65845 install.go:128] failed to install plugin "virt": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does not match, want: a4a8dd9b25c6abe83ed544e4262661805cef3d8353ba2ed03c7b7c8fb061a3a3, got 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5

since this passed our validation in #377 (https://travis-ci.org/kubernetes-sigs/krew-index/builds/620189954?utm_source=github_status&utm_medium=notification) I have suspicion that the release asset was updated after it's released.

cc: @dhiller

**Comment by eisraeli** [comment]
Hi guys, 
I'm experiencing the same issue.
Checksum does not match.

`$ kubectl krew install virt`

Resulting in:
```
Updated the local copy of plugin index.
Installing plugin: virt
W1219 12:11:29.579581   10909 install.go:132] failed to install plugin "virt": failed to dowload and move during installation: failed to download and verify file: checksum does not match, want: 45dee1e962164ea69c0a8c8d300d258007380f1e2b9d292e414719eacb69837e, got 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5
F1219 12:11:29.579678   10909 root.go:52] failed to install some plugins: [virt]

```
