### ISSUE TITLE
Fix skew plugin missing repository

### ISSUE THREAD

**Issue by brianpursley** [kubernetes-sigs/krew-index#4059]
During our monthly SIG-CLI bug scrub meeting, in a conversation we were wondering if there was a plugin for detecting (and failing for) unsupported client/server version skew.

We found that there is a [skew](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/skew.yaml) plugin in the index, but its [repository appears to be gone](https://github.com/dty1er/kubectl-skew).

As expected, attempting to install the plugin fails, since its release files are also missing.
```
kubectl krew install skew
```
```
Updated the local copy of plugin index.
  New plugins available:
    * alfred
    * cluster-compare
    * crust-gather
    * encrypted-kubeconfig
Installing plugin: skew
W0911 15:10:54.700425  498823 install.go:164] failed to install plugin "skew": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: failed to obtain plugin archive: failed to download "https://github.com/dty1er/kubectl-skew/releases/download/v0.0.3/kubectl-skew_0.0.3_Linux_x86_64.tar.gz", status code 404
failed to install some plugins: [skew]: install failed: failed to unpack into staging dir: failed to unpack the plugin archive: failed to obtain plugin archive: failed to download "https://github.com/dty1er/kubectl-skew/releases/download/v0.0.3/kubectl-skew_0.0.3_Linux_x86_64.tar.gz", status code 404
```

@hidetatz It looks like you [added this plugin to the index in 2021](https://github.com/kubernetes-sigs/krew-index/pull/991), but @dtyler1's account (who looks to have been the owner of the kubectl-skew repository) no longer exists. Do you know if there is another official location for this plugin or have any thoughts on how to proceed?

**Comment by brianpursley** [comment]
It's worth noting that for several releases now `kubectl version` itself will display a warning if you have an unsupported version skew.

What we were wondering is whether there was a plugin that would exit with a non-zero exit code if you are out of skew, so for example if you wanted to have some automated tooling that checks version skew and fails before proceeding.  I don't know if this plugin does this or not.

**Comment by ahmetb** [comment]
We should remove it. Normally, we don't allow someone who is not the author/maintainer of a plugin to submit it here on their behalf. This might've been a miss. 

Thanks for reporting @brianpursley. Feel free to send a PR to remove.
/kind bug
