### ISSUE TITLE
Gauging interest for a thin UI layer on krew plugin list

### ISSUE THREAD

**Issue by rajatjindal** [kubernetes-sigs/krew-index#416]
During holidays, I created a thin UI on top of list of plugins we have in krew-index repo. I wanted to gauge interest of this in the community. 

https://rajatjindal.com/krew

Thanks
Rajat Jindal

**Comment by ahmetb** [comment]
I am currently -1 because

1. it doesn’t significantly improve the experience and it’s yet another thing to maintain.

2. We should probably solve categorizing or tagging plugins first. https://github.com/kubernetes-sigs/krew/issues/406

Also it would be great if you make sure to exclude that page from search indexes with robots.txt, we don’t want to have two sources of truth. 😬

/kind proposal

**Comment by rajatjindal** [comment]
the data is dynamic and fetched from krew-index repo. But I get it if we do not want the cost of maintenance.

**Comment by ahmetb** [comment]
It might be a little early, but let's keep it open.

**Comment by corneliusweig** [comment]
I guess the data is pre-processed and cached here? https://tools-api.rajatjindal.com/krew

At the moment, the page doesn't really add anything which could not be done with `Ctrl+F` on our plugins overview. I also don't see a relevant use-case how we can help our users better to find the plugins they need with this tool. As Ahmet already said, our focus should be to improve the core `krew` features. I therefore think it does not make sense to make this an official view and maintain this.

But it's a nice overview and as long as it stays in sync with `krew-index`, it can't hurt. I'm sure it was a lot of fun to build it :)

**Comment by rajatjindal** [comment]
I've not enabled caching yet on that endpoint (that is indeed the endpoint which actually interacts with github, fetch all yamls, and change them to json objects for UI to consume) so its live data from repo.

for badges etc, i am using shields.io

my personal website i built using vue, so this plugin list is a very simple vue component in there. 

I will keep it there for now, and decide on the fate later. (started exploring how can i block search index from indexing it).
