### ISSUE TITLE
Add kubectl-terminate to krew-index

### ISSUE THREAD

**Issue by ishantanu** [kubernetes-sigs/krew-index#511]
Hi 👋

Opening this issue to explore the possibility of adding [kubectl-terminate](https://github.com/xcoulon/kubectl-terminate) to the krew-index and distributing it via krew.

CC @corneliusweig @xcoulon

**Comment by corneliusweig** [comment]
Thanks @ishantanu for bringing this up!

---

That plugin looks really good. I've never had such an issue but I imagine how painful it can be if it comes up. So I'd love to see it added. @xcoulon what do you think? Would you care to submit a manifest for it? The guide to write a manifest is here: https://github.com/kubernetes-sigs/krew/blob/master/docs/DEVELOPER_GUIDE.md

**Comment by ahmetb** [comment]
Something that removes finalizers, FINALLY! 😄

**Comment by xcoulon** [comment]
> Thanks @ishantanu for bringing this up!
> 
> That plugin looks really good. I've never had such an issue but I imagine how painful it can be if it comes up. So I'd love to see it added. @xcoulon what do you think? Would you care to submit a manifest for it? The guide to write a manifest is here: https://github.com/kubernetes-sigs/krew/blob/master/docs/DEVELOPER_GUIDE.md

hello @corneliusweig ! Sorry for the late response, I was AFK last week. 
Sure, I also thought about submitting this plugin but @ishantanu was faster than me ;) 
I'll take a look at the guide to write the manifest.

**Comment by ahmetb** [comment]
pinging if you're still interested @xcoulon.

**Comment by xcoulon** [comment]
ah yes, sorry, it slipped my mind. Thanks for the reminder, I'll try to give it a look soon!

**Comment by xcoulon** [comment]
I still haven't had time to take a look at it, sorry 😬

**Comment by ytsarev** [comment]
any chance it will get into the index? It is very useful plugin

**Comment by xcoulon** [comment]
> any chance it will get into the index? It is very useful plugin

hello @ytsarev ! thanks for the reminder and sorry for not taking care of this request earlier, I've been pretty busy but I will try to address it soon.
