### ISSUE TITLE
Fix unnecessary copies in example manifest

### ISSUE THREAD

**Issue by Eriner** [kubernetes-sigs/krew-index#624]
@ahmetb [commented in #623 that the copy wildcards are unnecessary](https://github.com/kubernetes-sigs/krew-index/pull/623#discussion_r431362916)

In that case, the [tree](https://github.com/kubernetes-sigs/krew-index/blob/7118d2a66853b0e22c6f3bc3c788547041685cc3/plugins/tree.yaml#L24) manifest [example](https://krew.sigs.k8s.io/docs/developer-guide/example-manifests/) should be fixed.

**Comment by corneliusweig** [comment]
Generally, that's a good idea. However, it needs to be fixed in the right places. For example, the manifest you are referring to, is generated by a template from here https://github.com/ahmetb/kubectl-tree/blob/3f3a78548b3cc3ceb9d06a2d71bda3490db14bf1/.krew.yaml#L24.

**Comment by ahmetb** [comment]
Yeah. We’ve started enforcing it at some point and a good number of the manifests are autogen’d by krew-release-bot. 

Happy to accept PRs to kubectl-tree repo as that’s listed as an example in dev docs. 

I wouldn’t bother with others, as we can address them later on when they need manual rev.
