### ISSUE TITLE
deprecate bad version

### ISSUE THREAD

**Issue by itaysk** [kubernetes-sigs/krew-index#743]
Hi, I have recently released v2 of kubectl-neat which turned out to be a low quality release, there were bugs and oversights on my end. I have now fixed it, and unfortunately had to make another breaking change to the cli so I will have to release the fix as v3. If I release it as v3, will v2 still be visible to krew users? if so, is there a way to delete it or make it clear that they should not use it? alternatively, if I release this fixed version as v2 (make a pr that changes just the hash of artifacts), can that be a problem for users?

**Comment by ahmetb** [comment]
/kind question

1. `krew install` always installs the latest available version
2. `krew upgrade` always upgrades to latest available version.
3. with (1) and (2) there's no way to install old versions a plugin with krew.
4. whether to upgrade a plugin or not depends entirely on the `version:` field in plugin manifest. if there's a greater version number available, plugin will be upgraded.
5. some users that have the old version may continue to use it for long times until they explicitly run `krew upgrade`.

hope this helps.

/close
