### ISSUE TITLE
Add darwin to net-forward os list

### ISSUE THREAD

**Issue by artemsablin** [kubernetes-sigs/krew-index#755]
[Net-forward](https://github.com/antitree/krew-net-forward) is a shell script and it works on my mac.

Can we add darwin to its os list? Right now trying to install it and getting
```
W0812 15:46:13.949696   28059 install.go:138] failed to install plugin "net-forward": plugin "net-forward" does not offer installation for this platform
```

unless I install it manually.

**Comment by artemsablin** [comment]
@ antitree

**Comment by artemsablin** [comment]
@antitree

**Comment by antitree** [comment]
This makes sense. Let me test it out.

**Comment by corneliusweig** [comment]
@artemsablin You could check this out yourself. Just enable the respective platform and run `krew install --no-update-index net-forward`.

**Comment by corneliusweig** [comment]
That said, this is issue belongs into https://github.com/antitree/krew-net-forward :wink:, so I'll close this one.
/close
