### ISSUE TITLE
Add cert-manager plugin

### ISSUE THREAD

**Issue by strigona-worksight** [kubernetes-sigs/krew-index#764]
https://cert-manager.io/docs/usage/kubectl-plugin/

Thanks in advance!

**Comment by ahmetb** [comment]
We don't track requests for plugins to be added here. We also already have this plugin. 

Please work with cert-manager maintainers and their repo if you need krew instructions documented there.

**Comment by strigona-worksight** [comment]
Ah thank you - my apologies. I had checked here and didn't see it listed: https://github.com/kubernetes-sigs/krew-index/blob/master/plugins.md
