### ISSUE TITLE
Include recent stats on the stats dashboard for all plugins

### ISSUE THREAD

**Issue by marccampbell** [kubernetes-sigs/krew-index#816]
The stats site is super interesting and helpful, thanks for creating and sharing this data publicly. 

Is it be possible to include a graph and stats for the plugin ecosystem that show trends and recency?  Currently, all I can find is total download counts, but I think it would be useful to include a "number of downloads in the past (week/month)" column or way to sort the ecosystem this way too?

**Comment by ahmetb** [comment]
Ideally if there's a GitHub app that tracks that over time, it would be the best. 

We track historical download stats for the Krew itself. I am not sure if the approach would scale well to hundreds of repos (given underlying repos change names etc). 

Let's discuss.

**Comment by corneliusweig** [comment]
If I understand correctly, you are looking for a moving average similar to what brew does. The data for that should be there, it's only a question how easy it is to make the respective graphs.

**Comment by corneliusweig** [comment]
@marccampbell are you still interested in this functionality? Otherwise we should close this issue.

**Comment by marccampbell** [comment]
@corneliusweig I do still like this and think it would be useful. If it's something I can contribute and agreeable, I'm happy to take this issue.
