### ISSUE TITLE
Remove certain node debugging plugins per 1.20 "debug" command

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew-index#950]
kubectl 1.20.0 introduces beta "kubectl debug" command that can run containers on the Node for debugging e.g.

    kubectl debug node/mynode -it --image=busybox

Certain plugins we have in krew-index are now potentially obsolete. Potentially:

- node-admin
- node-shell
- pod-shell (more like #949)
- debug-shell
- cssh
- ssh-jump

We should probably do a scan of this and see if we need to remove anything.

Some plugins listed above might still have a value add.

**Comment by verb** [comment]
@ahmetb Please let me know if you come across functionality that might be good to add to the `kubectl debug` built-in.
